import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./pages/Header";
import Sidebar from "./pages/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nikah_Khat_Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Header />
          <div className="container mx-auto flex">
            <Sidebar />
            <div className="w-9/12"> {children}</div>
            {/* Main content goes here */}
          </div>
        </div>
      </body>
    </html>
  );
}
